- home.html
> added new photo

- home.html
- style.css
Hey @Soumyajit2825 Here i Resolved the Provided issue of gap between and video and Images Divs and Changed the last image as it was not present in Image Directory so Check my PR
> Resolved the Gap Issue in Webpage

- style.css
this is how it looked before in mid & small sized screens
this is how it looks now in mid & small sized screens
> Responsiveness of stats-main table section fixed

- style.css
> added bg color and font

- index.html
Got a Minor text typo in **God of football ** section
And Removed <Span>
> Minor Text edit and Removed Unused Span.

- app.js
- index.html
- style.css
Hi @Soumyajit2825, I'm making a single PR for both issues #30  and #31 
Hope you liked my code
Thanks for working together :)
> This PR fixes both #30 and #31

- README.md
Add it with Hacktoberfest tag 
Thanks
> Updated  Readme Contributors list and Added index.html SS

- README.md
> added contributers list and website preview

- index.html
- style.css
Updated Navbar as per Requirement :-
Thanks
> Navbar Upgradation

- index.html
@Soumyajit2825 Just added hover play to video
> Added a Video hover play feature

- README.md
- index.html
> Removing Sign up/Login link

- index.html
- style.css
**Task1 :- The previous navbar code was commented and left above in the repo .**
So I removed that part.
**Task2 :- The blueish color was not that visible** 
So I changed the color of the Numbers to Golden that improve visibility of the numbers and match the title colors & logo .
> Removed Navbar Comment and Changed stats Number color for visibility

- index.html
- style.css
Big Screens
Mid Screens
Small Screens
> stats table responsiveness fixed

- index.html
> fixed the back to top button

- index.html
@Soumyajit2825 can u please assign me this issue
> facts section created

- index.html
- style.css
This is with respect to issue #63 
@Soumyajit2825 please take a look and tell me if you need some more improvements.
> Made facts section more beautiful

- style.css
Fixed the dark , light mode issue by changing the CSS
Title : Fixed the dark / light mode issue
Issue No. : 70
> Fixed the Dark / Light mode issue , issue #70

- index.html
- style.css
Title : Make the footer responsive and beautiful
Issue No. : #95
Close #93 
**Screnshots**
apertre24
> Make the footer responsive and beautiful

- index.html
- style.css
#98 
"cards not aligned to center"
Close #98
Under Apertre24
> css changes made

- style.css
Title :
Issue No. : #100 
Close #100 
**Screnshots**
> fixed photo section hover issue

- style.css
Title : Enhanced the scroll bar
Issue No. : #113 
Close #113
**Screnshots**
Apertre 24
> Enhanced the scrollbar

- app.js
- style.css
Title : Hamburger menu visibility improved
Issue No. : #106 
Close #106 
**Screenshots**
Apertre 24
> Improved visibility for hamburger menu

- style.css
Title : Make the STATS section responsive 
Issue No. : #131 
Close  issue : #131
**Screnshots**
apertre24
> Make The Website Responsive

- index.html
Title : Corrected the swapped pics
Issue No. : #144
Close #144
**Screenshots**
before:
after:
Pls review my changes @5h0ov @Soumyajit2825 
Apertre 24
> Corrected the swapped pics

- index.html
Title : Add Horizontal Scrollbar in Time line
Issue No. :#150
Close #150
**Screnshots**
Apertre24
> Add Horizontal Scrollbar in Time line
